// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RTMultiTenant.Api.Data;

#nullable disable

namespace RTMultiTenant.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RTMultiTenant.Api.Entities.CashExpense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("expense_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expense_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RtId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rt_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RtId", "ExpenseDate")
                        .HasDatabaseName("idx_rt_expense_date");

                    b.HasIndex("RtId", "IsActive")
                        .HasDatabaseName("idx_rt_active");

                    b.ToTable("cash_expenses", (string)null);
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.Contribution", b =>
                {
                    b.Property<Guid>("ContributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("contribution_id");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("admin_note");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("payment_date");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("period_start");

                    b.Property<string>("ProofImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("proof_image_path");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resident_id");

                    b.Property<Guid>("RtId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rt_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ContributionId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RtId")
                        .HasDatabaseName("idx_rt_contrib");

                    b.HasIndex("RtId", "ResidentId")
                        .HasDatabaseName("idx_rt_resident");

                    b.HasIndex("RtId", "Status")
                        .HasDatabaseName("idx_rt_status");

                    b.HasIndex("RtId", "PeriodStart", "PeriodEnd")
                        .HasDatabaseName("idx_rt_period");

                    b.ToTable("contributions", (string)null);
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.EventRecord", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("char(36)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("AggregateVersion")
                        .HasColumnType("int")
                        .HasColumnName("aggregate_version");

                    b.Property<Guid>("CausedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("caused_by_user_id");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("event_payload");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("RtId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rt_id");

                    b.HasKey("EventId");

                    b.HasIndex("CausedByUserId");

                    b.HasIndex("RtId", "AggregateId", "AggregateVersion")
                        .HasDatabaseName("idx_rt_agg_ver");

                    b.HasIndex("RtId", "AggregateType", "OccurredAt")
                        .HasDatabaseName("idx_rt_type_time");

                    b.HasIndex("RtId", "CausedByUserId", "OccurredAt")
                        .HasDatabaseName("idx_rt_user_time");

                    b.ToTable("event_store", (string)null);
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.MonthlyCashSummary", b =>
                {
                    b.Property<Guid>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("summary_id");

                    b.Property<decimal>("BalanceEnd")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("balance_end");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<Guid>("RtId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rt_id");

                    b.Property<decimal>("TotalContributionIn")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_contribution_in");

                    b.Property<decimal>("TotalExpenseOut")
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_expense_out");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("SummaryId");

                    b.HasIndex("RtId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("uq_rt_year_month");

                    b.ToTable("monthly_cash_summary", (string)null);
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.Resident", b =>
                {
                    b.Property<Guid>("ResidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("resident_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("ApprovalNote")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("approval_note");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("approval_status");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("gender");

                    b.Property<string>("KkDocumentPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("kk_document_path");

                    b.Property<string>("NationalIdNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("national_id_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("RtId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rt_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ResidentId");

                    b.HasIndex("RtId")
                        .HasDatabaseName("idx_rt_resident");

                    b.HasIndex("RtId", "ApprovalStatus")
                        .HasDatabaseName("idx_rt_status");

                    b.ToTable("residents", (string)null);
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.ResidentFamilyMember", b =>
                {
                    b.Property<Guid>("FamilyMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("family_member_id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("relationship");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resident_id");

                    b.Property<Guid>("RtId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rt_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("FamilyMemberId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RtId", "ResidentId")
                        .HasDatabaseName("idx_rt_family");

                    b.ToTable("resident_family_members", (string)null);
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.Rt", b =>
                {
                    b.Property<Guid>("RtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("rt_id");

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address_detail");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("province_name");

                    b.Property<string>("RtNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("rt_number");

                    b.Property<string>("RwNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("rw_number");

                    b.Property<string>("SubdistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subdistrict_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("village_name");

                    b.HasKey("RtId");

                    b.HasIndex("RtNumber", "RwNumber", "VillageName", "SubdistrictName", "CityName", "ProvinceName")
                        .IsUnique()
                        .HasDatabaseName("uq_rt_context");

                    b.ToTable("rt", (string)null);
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("resident_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("role");

                    b.Property<Guid>("RtId")
                        .HasColumnType("char(36)")
                        .HasColumnName("rt_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("RtId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.CashExpense", b =>
                {
                    b.HasOne("RTMultiTenant.Api.Entities.User", "CreatedBy")
                        .WithMany("CashExpenses")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RTMultiTenant.Api.Entities.Rt", "Rt")
                        .WithMany()
                        .HasForeignKey("RtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Rt");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.Contribution", b =>
                {
                    b.HasOne("RTMultiTenant.Api.Entities.Resident", "Resident")
                        .WithMany("Contributions")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RTMultiTenant.Api.Entities.Rt", "Rt")
                        .WithMany()
                        .HasForeignKey("RtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Rt");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.EventRecord", b =>
                {
                    b.HasOne("RTMultiTenant.Api.Entities.User", "CausedBy")
                        .WithMany()
                        .HasForeignKey("CausedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RTMultiTenant.Api.Entities.Rt", "Rt")
                        .WithMany()
                        .HasForeignKey("RtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CausedBy");

                    b.Navigation("Rt");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.MonthlyCashSummary", b =>
                {
                    b.HasOne("RTMultiTenant.Api.Entities.Rt", "Rt")
                        .WithMany()
                        .HasForeignKey("RtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rt");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.Resident", b =>
                {
                    b.HasOne("RTMultiTenant.Api.Entities.Rt", "Rt")
                        .WithMany()
                        .HasForeignKey("RtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rt");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.ResidentFamilyMember", b =>
                {
                    b.HasOne("RTMultiTenant.Api.Entities.Resident", "Resident")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RTMultiTenant.Api.Entities.Rt", "Rt")
                        .WithMany()
                        .HasForeignKey("RtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Rt");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.User", b =>
                {
                    b.HasOne("RTMultiTenant.Api.Entities.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId");

                    b.HasOne("RTMultiTenant.Api.Entities.Rt", "Rt")
                        .WithMany("Users")
                        .HasForeignKey("RtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resident");

                    b.Navigation("Rt");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.Resident", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.Rt", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RTMultiTenant.Api.Entities.User", b =>
                {
                    b.Navigation("CashExpenses");
                });
#pragma warning restore 612, 618
        }
    }
}
